name: Test

on: pull_request

jobs:
  test:
    name: Test and lint code base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install --ignore-engines
    - run: npm run test
    - run: npm run lint
  build:
    name: Trial build of the codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --ignore-engines
      - run: npm run build